version: "3"

services:
  node:
    image: node:16
    container_name: trybers_and_dragons
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app

networks:
  default:
    name: trybers_and_dragons_net
